name: Test container image build
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-image:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      cache: true

  build-image-streaming:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-streaming
      cancel-in-progress: true

    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      cache: true
